apiVersion: skaffold/v3
kind: Config
deploy:
  kubectl: {}
manifests:
  rawYaml:
    - "./infra/k8s/*"
build:
  local:
    push: false
  artifacts:
    - image: sowrerajan/auth-service
      context: auth-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
