apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: sowrerajan/appointment-service
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret-key
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: appointment-service-srv
spec:
  selector:
    app: appointment-service
  ports:
    - name: appointment-service
      protocol: TCP
      port: 3001
      targetPort: 3001
